# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[8, 7, 9, 8, 7, 2, 0, 7, 2, 1, 2, 2],
       [7, 0, 0, 8, 6, 9, 0, 1, 9, 9, 2, 4],
       [0, 4, 3, 7, 0, 6, 4, 4, 3, 8, 0, 8],
       [9, 0, 5, 5, 5, 7, 8, 7, 0, 9, 1, 6],
       [3, 0, 8, 2, 5, 0, 0, 7, 7, 0, 2, 2],
       [7, 0, 3, 1, 4, 2, 6, 4, 8, 7, 3, 2],
       [9, 1, 2, 1, 1, 4, 3, 3, 9, 3, 2, 7],
       [4, 7, 0, 1, 4, 1, 3, 0, 2, 5, 0, 4],
       [6, 7, 4, 2, 3, 8, 9, 0, 9, 3, 6, 4],
       [9, 6, 7, 3, 9, 0, 3, 6, 2, 4, 7, 5],
       [1, 4, 1, 7, 9, 6, 0, 7, 0, 9, 8, 0],
       [3, 5, 8, 6, 2, 7, 4, 0, 5, 0, 0, 5]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int)

In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[8, 7, 9, 8, 7, 2, 0, 7, 2, 1, 2, 2],
       [7, 0, 0, 8, 6, 9, 0, 1, 9, 9, 2, 4],
       [0, 4, 3, 7, 0, 6, 4, 4, 3, 8, 0, 8],
       [9, 0, 5, 5, 5, 7, 8, 7, 0, 9, 1, 6],
       [3, 0, 8, 2, 5, 0, 0, 7, 7, 0, 2, 2],
       [7, 0, 3, 1, 4, 2, 6, 4, 8, 7, 3, 2],
       [9, 1, 2, 1, 1, 4, 3, 3, 9, 3, 2, 7],
       [4, 7, 0, 1, 4, 1, 3, 0, 2, 5, 0, 4],
       [6, 7, 4, 2, 3, 8, 9, 0, 9, 3, 6, 4],
       [9, 6, 7, 3, 9, 0, 3, 6, 2, 4, 7, 5],
       [1, 4, 1, 7, 9, 6, 0, 7, 0, 9, 8, 0],
       [3, 5, 8, 6, 2, 7, 4, 0, 5, 0, 0, 5]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, -18, -20,  11,   0,  22, -14, -16,  21,  16,  -7,   0],
       [  0,  13,  -4,  12, -24,   4,  -2,   1,  -9,  11, -19,   0],
       [  0, -18,   4,   1,   3,   9,  14,   9, -26,  27, -13,   0],
       [  0, -11,  22, -11,   9, -14, -21,  10,  13, -25,   2,   0],
       [  0, -11,   1,  -6,   7,  -6,  15,  -8,   5,  14,  -1,   0],
       [  0, -14,   3,  -1,  -9,   9,  -4,  -4,  20, -11,  -5,   0],
       [  0,  16, -14,  -3,  10, -15,  -1,  -8, -15,  12, -17,   0],
       [  0,   5,   0,  -3, -11,  19,  22, -24,  29, -12,  10,   0],
       [  0,  -3,  14, -13,  21, -26,  -3,  12, -11,  -5,   5,   0],
       [  0,   3, -22,   9,  12,   8, -20,  22, -23,  24,  16,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [16]:
img = cv2.imread('lena.png', 0)

In [17]:
h,w=img.shape

In [18]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [19]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [ ]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()